#!/bin/bash

##SCZ
java -Xmx20g -jar kggsee_path/kggsee.jar  --nt 10 --vcf-ref genotype_path/eas_hg19/1kg.phase3.v5.shapeit2.eas.hg19.chr_CHROM_.vcf.gz --sum-file gwas_result_path/gwas_file/SCZ/PGC3_Nature/PGC3_SCZ_wave3.asian.autosome.public.v3.vcf.tsv --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_peturbation_file/hipsc_ctrl_with_se_drug_induced_foldchange.txt  --out ./SCZ_Asian_CTRL_NPC_top_1000_gene_p_fixed_0.05 --dese-permu-num 100  --multiple-testing fixed  --p-value-cutoff 0.05 --calc-selectivity false --chrom-col CHROM --p-col PVAL --pos-col POS --top-gene 1000 &&
java -Xmx20g -jar kggsee_path/kggsee.jar  --nt 10 --vcf-ref genotype_path/eas_hg19/1kg.phase3.v5.shapeit2.eas.hg19.chr_CHROM_.vcf.gz --sum-file gwas_result_path/gwas_file/SCZ/PGC3_Nature/PGC3_SCZ_wave3.asian.autosome.public.v3.vcf.tsv --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_peturbation_file/hipsc_sz_with_se_drug_induced_foldchange.txt  --out ./SCZ_Asian_SZ_NPC_top_1000_gene_p_fixed_0.05 --dese-permu-num 100  --multiple-testing fixed  --p-value-cutoff 0.05 --calc-selectivity false --chrom-col CHROM --p-col PVAL --pos-col POS --top-gene 1000 &&
java -Xmx20g -jar kggsee_path/kggsee.jar  --nt 10 --vcf-ref genotype_path/afr/AFR/1kg.phase3.v5.shapeit2.afr.hg19.chr_CHROM_.vcf.gz --sum-file gwas_result_path/gwas_file/SCZ/PGC3_Nature/PGC3_SCZ_wave3.afram.autosome.public.v3.vcf.tsv --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_peturbation_file/hipsc_ctrl_with_se_drug_induced_foldchange.txt  --out ./SCZ_AFR_CTRL_NPC_top_1000_gene_p_fixed_0.05 --dese-permu-num 100  --multiple-testing fixed  --p-value-cutoff 0.05 --calc-selectivity false --chrom-col CHROM --p-col PVAL --pos-col POS --top-gene 1000 &&
java -Xmx20g -jar kggsee_path/kggsee.jar  --nt 10 --vcf-ref genotype_path/afr/AFR/1kg.phase3.v5.shapeit2.afr.hg19.chr_CHROM_.vcf.gz --sum-file gwas_result_path/gwas_file/SCZ/PGC3_Nature/PGC3_SCZ_wave3.afram.autosome.public.v3.vcf.tsv --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_peturbation_file/hipsc_sz_with_se_drug_induced_foldchange.txt  --out ./SCZ_AFR_SZ_NPC_top_1000_gene_p_fixed_0.05 --dese-permu-num 100  --multiple-testing fixed  --p-value-cutoff 0.05 --calc-selectivity false --chrom-col CHROM --p-col PVAL --pos-col POS --top-gene 1000

##MDD
java -Xmx20g -jar kggsee_path/kggsee.jar  --nt 10 --vcf-ref genotype_path/eas_hg19/1kg.phase3.v5.shapeit2.eas.hg19.chr_CHROM_.vcf.gz --sum-file gwas_file_path/MDD/jamapsy_Giannakopoulou_2021_exclude_whi_23andMe.txt --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_perturbation_file_path/hipsc_ctrl_with_se_drug_induced_foldchange.txt  --out ./MDD_Asian_CTRL_NPC_top_1000_gene_p_fixed_0.05 --dese-permu-num 100  --multiple-testing fixed  --p-value-cutoff 0.05 --calc-selectivity false --top-gene 1000 --chrom-col chr --pos-col pos --p-col P.Neff &&
java -Xmx20g -jar kggsee_path/kggsee.jar  --nt 10 --vcf-ref genotype_path/eas_hg19/1kg.phase3.v5.shapeit2.eas.hg19.chr_CHROM_.vcf.gz --sum-file gwas_file_path/MDD/jamapsy_Giannakopoulou_2021_exclude_whi_23andMe.txt --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_perturbation_file_path/hipsc_sz_with_se_drug_induced_foldchange.txt  --out ./MDD_Asian_SZ_NPC_top_1000_gene_p_fixed_0.05 --dese-permu-num 100  --multiple-testing fixed  --p-value-cutoff 0.05 --calc-selectivity false --top-gene 1000 --chrom-col chr --pos-col pos --p-col P.Neff 
