
#!/bin/bash
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/MCF7_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_MCF7  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false &&
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/PC3_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_PC3  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false &&
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/A375_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_A375  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false &&
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/A549_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_A549  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/HCC515_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_HCC515  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false &&
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/HA1E_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_HA1E  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false &&
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/HT29_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_HT29  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false &&
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/HEPG2_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_HEPG2  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false
java -Xmx20g -jar kggsee_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_path/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz  --sum-file gwas_file_path/SCZ/daner_PGC_SCZ_w3_90_0518d_eur.gz --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file ./drug_perturbation_with_se/VCAP_6H_drug_induced_foldchange_se.txt --out ./result/LINCS_non_neuro_cell/scz_lincs_6h_VCAP  --dese-permu-num 100  --multiple-testing bonf  --p-value-cutoff 0.05 --calc-selectivity false
