
#!/bin/bash
#Control NPC
java -Xmx20g -jar kggsee_file_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_file/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz --sum-file gwas_summary_file/cad.add.160614.website.txt --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file drug_perturbation_file/hipsc_ctrl_with_se_drug_induced_foldchange.txt --out cad_CTRL_NPC_update_no_calcu_benfdr0.01  --dese-permu-num 100  --multiple-testing benfdr  --p-value-cutoff 0.01 --calc-selectivity false &&
java -Xmx20g -jar kggsee_file_path/kggsee.jar  --nt 10 --vcf-ref genotype_file/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz --sum-file gwas_summary_file/EUR_all_auto-10-2021_chr.txt --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_perturbation_file/hipsc_ctrl_with_se_drug_induced_foldchange.txt  --out ra_CTRL_NPC_update_no_calcu_benfdr0.01  --dese-permu-num 100  --multiple-testing benfdr  --p-value-cutoff 0.01 --calc-selectivity false &&

#SZ NPC
java -Xmx20g -jar kggsee_file_path/kggsee.jar --nt 10 --buildver hg19 --vcf-ref genotype_file/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz --sum-file gwas_summary_file/cad.add.160614.website.txt --filter-maf-le 0.05  --db-gene refgene  --gene-condi  --regions-out chr6:28477797-33448354  --expression-file drug_perturbation_file/hipsc_sz_with_se_drug_induced_foldchange.txt --out cad_SZ_NPC_update_no_calcu_benfdr_0.01  --dese-permu-num 100  --multiple-testing benfdr   --p-value-cutoff 0.01 --calc-selectivity false &&
java -Xmx20g -jar kggsee_file_path/kggsee.jar  --nt 10 --vcf-ref genotype_file/eur/1kg.phase3.v5.shapeit2.eur.hg19.chr_CHROM_.vcf.gz --sum-file gwas_summary_file/EUR_all_auto-10-2021_chr.txt --filter-maf-le 0.05  --db-gene refgene  --gene-condi   --regions-out chr6:28477797-33448354  --expression-file drug_perturbation_file/hipsc_sz_with_se_drug_induced_foldchange.txt  --out ra_SZ_NPC_update_no_calcu_benfdr_0.01  --dese-permu-num 100  --multiple-testing benfdr   --p-value-cutoff 0.01 --calc-selectivity false 
